platform :ios, '13.0'
use_frameworks! :linkage => :static

source 'https://cdn.cocoapods.org'

def pod_Common
  pod 'JSLayoutSizeFit', :path => '..', :subspecs => ['ExtensionForSwift']
  pod 'QMUIKit'
  pod 'Masonry'
  pod 'MPITextKit'
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']
end

target 'JSLayoutSizeFitExample' do
  pod_Common
end

target 'JSLayoutSizeFitExampleMacOS' do
  pod_Common
end
