platform :ios, "10.0"
use_frameworks! :linkage => :static

source "https://github.com/CocoaPods/Specs.git"

def pod_Common
  pod "JSLayoutSizeFit", :path => "..", :subspecs => ["ExtensionForSwift"]
  pod "JSCoreKit", :path => "../../JSCoreKit"
  pod "QMUIKit"
  pod "Masonry"
  pod "MPITextKit"
end

target "JSLayoutSizeFitExample" do
  pod_Common
  pod "LookinServer", "~> 1.0.4", :configurations => ["Debug"]
  pod "MLeaksFinder", :configurations => ["Debug"]
  pod "FBRetainCycleDetector", :git => "https://github.com/jiasongs/FBRetainCycleDetector.git", :configurations => ["Debug"]
end

target "JSLayoutSizeFitExampleMacOS" do
  pod_Common
end
